### ISSUE TITLE
Some drawbacks I have to tell you

### ISSUE THREAD

**Issue by Kusto-M** [NinaM31/DeepLearning-FromPaper#1]
This model is not good, while it actually can work just in the special size Image.
Firstly, I have seen that you often use Relu activation, but Gelu is more good.
Other aspects, this model cannot suit for any input size Image.
Because I don't know why if I use a picture and its width or height more than 100px or 150px, and the runtime error will happen.
This is really bad for users, if this model cannot suit for a picture, just normal picture, and explaining the situation is a sensible choice.
Test this program and to declare the maximum size is what for the input Image.

**Comment by NinaM31** [comment]
Thank you very much @cherrise28 for this issue. I'll work on it 👍
